### ISSUE TITLE
运行这个python project_feature.py指令时一直报这个错是为什么？

### ISSUE THREAD

**Issue by zyjhxd** [SooLab/Part2Object#4]
Traceback (most recent call last):
  File "project_feature.py", line 158, in <module>
    scene = torch.load(os.path.join(SCANNET_DATA, "train", scene_id)+".pth")["coord"]
  File "/root/miniconda3/envs/part2object/lib/python3.8/site-packages/torch/serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/root/miniconda3/envs/part2object/lib/python3.8/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/root/miniconda3/envs/part2object/lib/python3.8/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'data/train/.ipynb_checkpoints.pth'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "project_feature.py", line 160, in <module>
    scene = torch.load(os.path.join(SCANNET_DATA, "val", scene_id)+".pth")["coord"]
  File "/root/miniconda3/envs/part2object/lib/python3.8/site-packages/torch/serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/root/miniconda3/envs/part2object/lib/python3.8/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/root/miniconda3/envs/part2object/lib/python3.8/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'data/val/.ipynb_checkpoints.pth'

**Comment by zhangyl4** [comment]
We iterate over all the scenarios by iterating over all the files under "data/frames_square/". You can iterate over all the scenarios of scannet in other ways such as the original scan file list or the training set validation set split.txt file. The cause of your error may be that the folder is mixed with other files that are not scannet scenes. You can manually clear it or add a judgment condition to solve it.

**Comment by LydJason** [comment]
> We iterate over all the scenarios by iterating over all the files under "data/frames_square/". You can iterate over all the scenarios of scannet in other ways such as the original scan file list or the training set validation set split.txt file. The cause of your error may be that the folder is mixed with other files that are not scannet scenes. You can manually clear it or add a judgment condition to solve it.

Hi @zhangyl4 ! I have this problem too. I think this issue is similar as the issues #6 and #2 . It seems that the original data provided by scannet does not contain files end with `.pth`, while the prepocess code `data_prepare_ScanNet.py` output files endwith `.ply`. I'm quite confused about how to find these `.pth` data, please correct me if I am wrong, thank you!
